language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      before_install:
        - brew tap caskroom/cask
        - brew cask install powershell
  fast_finish: true

# install:
#   - pwsh -f "josephdrane/pwshtf/install-dependencies.ps1"

# before_script:
#   - pwsh -f "josephdrane/pwshtf/build.ps1"

script:
  - pwsh -File './app/tf_install.test.ps1'

# after_success:
#   - pwsh -f "josephdrane/pwshtf/deploy.ps1"